
child_modules:
  - name: module1
    # version: 1.0.0
    # module_string: ghcr.io/netcracker/qubership-opensearch-integration-tests:${version}
  - name: module2
    # version: 2.0.0
    # module_string: ghcr.io/netcracker/qubership-deployment-status-provisioner:${version}
  - name: module3
    # version: 3.0.0
    # module_string: ghcr.io/netcracker/qubership-opensearch-dbaas-adapter:${version}

config_file: charts/values.yaml
