name: ArangoDB buld

on:
  workflow_dispatch:
    inputs:
      arango-version:
        type: string
        default: '3.11.14'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'arangodb/oskar'
          ref: arangodb-${{ inputs.arango-version }}
      - shell: bash
        run: |      
          sudo apt-get install -y fish
          fish -c "source helper.fish; and checkoutArangoDB; and community; and buildStaticArangoDB"
  
