name: "Build RabbitMQ"
on:
  workflow_dispatch:
    inputs:
      rabbitmq-version:
        description: "RabbitMQ version to build"
        required: true
        default: "v4.1.2"
permissions:
  contents: read
jobs:
  build-rabbitmq:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.rabbitmq-version }}
          repository: "rabbitmq/rabbitmq-server"
      - name: "Install pre-requisites"
        run: |
          sudo apt-get update
          # Skip installing pacakge docs {makes the man-db trigger much faster)
          sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
          path-exclude /usr/share/doc/*
          path-exclude /usr/share/man/*
          path-exclude /usr/share/info/*
          EOF
          sudo add-apt-repository ppa:rabbitmq/rabbitmq-erlang
          sudo apt-get update
          sudo apt-get install -y git elixir erlang erlang-nox erlang-dev erlang-src xmlto
          sudo snap install libxslt
      - name: "Build RabbitMQ"
        run: |
          make
      - name: "Build RabbitMQ package"
        run: |
          make make package-deb
      - name: "Upload RabbitMQ build artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: rabbitmq-build
          path: "rabbitmq-server/ebin/*"
