name: cert-manager-build
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          repository: cert-manager/cert-manager
          ref: v1.18.2
      - name: preparation
        run: |
          make vendor-go
          make go-workspace
      - name: build
        run: |
          # Build just the controller containers on every architecture
          make cert-manager-controller-linux
          make cert-manager-webhook-linux
          make cert-manager-cainjector-linux
          make cert-manager-acmesolver-linux
          #make cert-manager-ctl-linux
          make helm-chart
          make static-manifests
          #make GOMAXPROCS=2 -j4 release-artifacts
      - name: test
        run: |
          make unit-test
