---

name: PR Labeler Trigger
run-name: PR Labeler Trigger - ${{ github.event.pull_request.number }}
description: "Trigger the PR Labeler workflow when a PR is opened, synchronized, or reopened."
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  pr-labeler-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PR Labeler
        uses: netcracker/qubership-workflow-hub/actions/custom-event@main
        with:
          event-type: "pr-labeler-trigger"
          client-payload: '{"pr-number": "${{ github.event.pull_request.number }}"}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.pull_request.base.repo.name }}
          owner: ${{ github.event.pull_request.base.repo.owner.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }}
